version: '3'

services:
  project:
    build:
      args:
        user: estima
        uid: 1000
      dockerfile: Dockerfile
      context: ./
    restart: unless-stopped
    volumes:
      - ./project:/var/www/html/
    ports:
      - "8103:80"
      - "8444:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
