version: "3"

services:
  personalwebsite:
    build:
      args:
        user: estima
        uid: 1000
      dockerfile: Dockerfile
      context: ./
    restart: unless-stopped
    volumes:
      - ./PersonalWebsite:/var/www/html/
    ports:
      - "8201:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  adminer:
    build:
      args:
        user: estima
        uid: 1000
      dockerfile: Dockerfile
      context: ./
    restart: unless-stopped
    volumes:
      - ./Admin:/var/www/html/
    ports:
      - "8202:80"
      - "8448:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
