version: '3'

services:
  project:
    build:
      args:
        user: joaoestima
        uid: 1000
      dockerfile: Dockerfile
      context: ./
    restart: unless-stopped
    volumes:
      - ./project:/var/www/html/
    ports:
      - "8101:80"
      - "8447:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
